### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-9: ordinal not in range(128)

### ISSUE THREAD

**Issue by ahbon123** [ZeevG/python-dominant-image-colour#1]
Hello, I get an EncodeError, could you help me to fix it? Thanks.

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/opt/pycharm/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-9: ordinal not in range(128)

```

**Comment by ahbon123** [comment]
Solved by adding:
```
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
```
